/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404/': RouteRecordInfo<
      '/404/',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin//': RouteRecordInfo<
      '/admin//',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/answers/': RouteRecordInfo<
      '/admin/answers/',
      '/admin/answers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/articles/': RouteRecordInfo<
      '/admin/articles/',
      '/admin/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/comments/': RouteRecordInfo<
      '/admin/comments/',
      '/admin/comments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/': RouteRecordInfo<
      '/admin/options/',
      '/admin/options',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/components/carousel': RouteRecordInfo<
      '/admin/options/components/carousel',
      '/admin/options/components/carousel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/components/theme': RouteRecordInfo<
      '/admin/options/components/theme',
      '/admin/options/components/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/components/typed': RouteRecordInfo<
      '/admin/options/components/typed',
      '/admin/options/components/typed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/info': RouteRecordInfo<
      '/admin/options/info',
      '/admin/options/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/mail': RouteRecordInfo<
      '/admin/options/mail',
      '/admin/options/mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/oauth': RouteRecordInfo<
      '/admin/options/oauth',
      '/admin/options/oauth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/options/theme': RouteRecordInfo<
      '/admin/options/theme',
      '/admin/options/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/questions/': RouteRecordInfo<
      '/admin/questions/',
      '/admin/questions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/replys/': RouteRecordInfo<
      '/admin/replys/',
      '/admin/replys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reports/': RouteRecordInfo<
      '/admin/reports/',
      '/admin/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/topics/': RouteRecordInfo<
      '/admin/topics/',
      '/admin/topics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/user_groups/': RouteRecordInfo<
      '/admin/user_groups/',
      '/admin/user_groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users/': RouteRecordInfo<
      '/admin/users/',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/article/': RouteRecordInfo<
      '/client/article/',
      '/client/article',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/article/index-v1': RouteRecordInfo<
      '/client/article/index-v1',
      '/client/article/index-v1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/articles/': RouteRecordInfo<
      '/client/articles/',
      '/client/articles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/articles/index copy': RouteRecordInfo<
      '/client/articles/index copy',
      '/client/articles/index%20copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/badges/': RouteRecordInfo<
      '/client/badges/',
      '/client/badges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/': RouteRecordInfo<
      '/client/home/',
      '/client/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/carousel/carousel': RouteRecordInfo<
      '/client/home/components/carousel/carousel',
      '/client/home/components/carousel/carousel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/carousel/carousel-v1': RouteRecordInfo<
      '/client/home/components/carousel/carousel-v1',
      '/client/home/components/carousel/carousel-v1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/header/': RouteRecordInfo<
      '/client/home/components/header/',
      '/client/home/components/header',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/items/': RouteRecordInfo<
      '/client/home/components/items/',
      '/client/home/components/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/text-play/': RouteRecordInfo<
      '/client/home/components/text-play/',
      '/client/home/components/text-play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/topics/': RouteRecordInfo<
      '/client/home/components/topics/',
      '/client/home/components/topics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/home/components/topics/index-v1': RouteRecordInfo<
      '/client/home/components/topics/index-v1',
      '/client/home/components/topics/index-v1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/info/': RouteRecordInfo<
      '/client/info/',
      '/client/info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/info/index copy': RouteRecordInfo<
      '/client/info/index copy',
      '/client/info/index%20copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/login/': RouteRecordInfo<
      '/client/login/',
      '/client/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/notifications/': RouteRecordInfo<
      '/client/notifications/',
      '/client/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/notifications/setting/': RouteRecordInfo<
      '/client/notifications/setting/',
      '/client/notifications/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/question/': RouteRecordInfo<
      '/client/question/',
      '/client/question',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/question/components/comment-button/': RouteRecordInfo<
      '/client/question/components/comment-button/',
      '/client/question/components/comment-button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/question/index-v1': RouteRecordInfo<
      '/client/question/index-v1',
      '/client/question/index-v1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/questions/': RouteRecordInfo<
      '/client/questions/',
      '/client/questions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/questions/index copy': RouteRecordInfo<
      '/client/questions/index copy',
      '/client/questions/index%20copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/questions/index copy 2': RouteRecordInfo<
      '/client/questions/index copy 2',
      '/client/questions/index%20copy%202',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/settings/': RouteRecordInfo<
      '/client/settings/',
      '/client/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/signin/': RouteRecordInfo<
      '/client/signin/',
      '/client/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/topic/': RouteRecordInfo<
      '/client/topic/',
      '/client/topic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/topic/components/contexts/': RouteRecordInfo<
      '/client/topic/components/contexts/',
      '/client/topic/components/contexts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/topic/components/topic/': RouteRecordInfo<
      '/client/topic/components/topic/',
      '/client/topic/components/topic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/topics/': RouteRecordInfo<
      '/client/topics/',
      '/client/topics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/user/': RouteRecordInfo<
      '/client/user/',
      '/client/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/user/components/contexts/': RouteRecordInfo<
      '/client/user/components/contexts/',
      '/client/user/components/contexts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/user/components/user/': RouteRecordInfo<
      '/client/user/components/user/',
      '/client/user/components/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/users/': RouteRecordInfo<
      '/client/users/',
      '/client/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/client/users/components/item/': RouteRecordInfo<
      '/client/users/components/item/',
      '/client/users/components/item',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install//': RouteRecordInfo<
      '/install//',
      '/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install//1/': RouteRecordInfo<
      '/install//1/',
      '/install/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install//2/': RouteRecordInfo<
      '/install//2/',
      '/install/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install//3/': RouteRecordInfo<
      '/install//3/',
      '/install/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/install//4/': RouteRecordInfo<
      '/install//4/',
      '/install/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new-install/': RouteRecordInfo<
      '/new-install/',
      '/new-install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/': RouteRecordInfo<
      '/test/',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/page/user': RouteRecordInfo<
      '/test/page/user',
      '/test/page/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/xunzhang': RouteRecordInfo<
      '/test/xunzhang',
      '/test/xunzhang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/404/index.vue': {
      routes:
        | '/404/'
      views:
        | never
    }
    'src/pages/admin/index/index.vue': {
      routes:
        | '/admin//'
      views:
        | never
    }
    'src/pages/admin/answers/index.vue': {
      routes:
        | '/admin/answers/'
      views:
        | never
    }
    'src/pages/admin/articles/index.vue': {
      routes:
        | '/admin/articles/'
      views:
        | never
    }
    'src/pages/admin/comments/index.vue': {
      routes:
        | '/admin/comments/'
      views:
        | never
    }
    'src/pages/admin/options/index.vue': {
      routes:
        | '/admin/options/'
      views:
        | never
    }
    'src/pages/admin/options/components/carousel.vue': {
      routes:
        | '/admin/options/components/carousel'
      views:
        | never
    }
    'src/pages/admin/options/components/theme.vue': {
      routes:
        | '/admin/options/components/theme'
      views:
        | never
    }
    'src/pages/admin/options/components/typed.vue': {
      routes:
        | '/admin/options/components/typed'
      views:
        | never
    }
    'src/pages/admin/options/info.vue': {
      routes:
        | '/admin/options/info'
      views:
        | never
    }
    'src/pages/admin/options/mail.vue': {
      routes:
        | '/admin/options/mail'
      views:
        | never
    }
    'src/pages/admin/options/oauth.vue': {
      routes:
        | '/admin/options/oauth'
      views:
        | never
    }
    'src/pages/admin/options/theme.vue': {
      routes:
        | '/admin/options/theme'
      views:
        | never
    }
    'src/pages/admin/questions/index.vue': {
      routes:
        | '/admin/questions/'
      views:
        | never
    }
    'src/pages/admin/replys/index.vue': {
      routes:
        | '/admin/replys/'
      views:
        | never
    }
    'src/pages/admin/reports/index.vue': {
      routes:
        | '/admin/reports/'
      views:
        | never
    }
    'src/pages/admin/topics/index.vue': {
      routes:
        | '/admin/topics/'
      views:
        | never
    }
    'src/pages/admin/user_groups/index.vue': {
      routes:
        | '/admin/user_groups/'
      views:
        | never
    }
    'src/pages/admin/users/index.vue': {
      routes:
        | '/admin/users/'
      views:
        | never
    }
    'src/pages/client/article/index.vue': {
      routes:
        | '/client/article/'
      views:
        | never
    }
    'src/pages/client/article/index-v1.vue': {
      routes:
        | '/client/article/index-v1'
      views:
        | never
    }
    'src/pages/client/articles/index.vue': {
      routes:
        | '/client/articles/'
      views:
        | never
    }
    'src/pages/client/articles/index copy.vue': {
      routes:
        | '/client/articles/index copy'
      views:
        | never
    }
    'src/pages/client/badges/index.vue': {
      routes:
        | '/client/badges/'
      views:
        | never
    }
    'src/pages/client/home/index.vue': {
      routes:
        | '/client/home/'
      views:
        | never
    }
    'src/pages/client/home/components/carousel/carousel.vue': {
      routes:
        | '/client/home/components/carousel/carousel'
      views:
        | never
    }
    'src/pages/client/home/components/carousel/carousel-v1.vue': {
      routes:
        | '/client/home/components/carousel/carousel-v1'
      views:
        | never
    }
    'src/pages/client/home/components/header/index.vue': {
      routes:
        | '/client/home/components/header/'
      views:
        | never
    }
    'src/pages/client/home/components/items/index.vue': {
      routes:
        | '/client/home/components/items/'
      views:
        | never
    }
    'src/pages/client/home/components/text-play/index.vue': {
      routes:
        | '/client/home/components/text-play/'
      views:
        | never
    }
    'src/pages/client/home/components/topics/index.vue': {
      routes:
        | '/client/home/components/topics/'
      views:
        | never
    }
    'src/pages/client/home/components/topics/index-v1.vue': {
      routes:
        | '/client/home/components/topics/index-v1'
      views:
        | never
    }
    'src/pages/client/info/index.vue': {
      routes:
        | '/client/info/'
      views:
        | never
    }
    'src/pages/client/info/index copy.vue': {
      routes:
        | '/client/info/index copy'
      views:
        | never
    }
    'src/pages/client/login/index.vue': {
      routes:
        | '/client/login/'
      views:
        | never
    }
    'src/pages/client/notifications/index.vue': {
      routes:
        | '/client/notifications/'
      views:
        | never
    }
    'src/pages/client/notifications/setting/index.vue': {
      routes:
        | '/client/notifications/setting/'
      views:
        | never
    }
    'src/pages/client/question/index.vue': {
      routes:
        | '/client/question/'
      views:
        | never
    }
    'src/pages/client/question/components/comment-button/index.vue': {
      routes:
        | '/client/question/components/comment-button/'
      views:
        | never
    }
    'src/pages/client/question/index-v1.vue': {
      routes:
        | '/client/question/index-v1'
      views:
        | never
    }
    'src/pages/client/questions/index.vue': {
      routes:
        | '/client/questions/'
      views:
        | never
    }
    'src/pages/client/questions/index copy.vue': {
      routes:
        | '/client/questions/index copy'
      views:
        | never
    }
    'src/pages/client/questions/index copy 2.vue': {
      routes:
        | '/client/questions/index copy 2'
      views:
        | never
    }
    'src/pages/client/settings/index.vue': {
      routes:
        | '/client/settings/'
      views:
        | never
    }
    'src/pages/client/signin/index.vue': {
      routes:
        | '/client/signin/'
      views:
        | never
    }
    'src/pages/client/topic/index.vue': {
      routes:
        | '/client/topic/'
      views:
        | never
    }
    'src/pages/client/topic/components/contexts/index.vue': {
      routes:
        | '/client/topic/components/contexts/'
      views:
        | never
    }
    'src/pages/client/topic/components/topic/index.vue': {
      routes:
        | '/client/topic/components/topic/'
      views:
        | never
    }
    'src/pages/client/topics/index.vue': {
      routes:
        | '/client/topics/'
      views:
        | never
    }
    'src/pages/client/user/index.vue': {
      routes:
        | '/client/user/'
      views:
        | never
    }
    'src/pages/client/user/components/contexts/index.vue': {
      routes:
        | '/client/user/components/contexts/'
      views:
        | never
    }
    'src/pages/client/user/components/user/index.vue': {
      routes:
        | '/client/user/components/user/'
      views:
        | never
    }
    'src/pages/client/users/index.vue': {
      routes:
        | '/client/users/'
      views:
        | never
    }
    'src/pages/client/users/components/item/index.vue': {
      routes:
        | '/client/users/components/item/'
      views:
        | never
    }
    'src/pages/install/index/index.vue': {
      routes:
        | '/install//'
      views:
        | never
    }
    'src/pages/install/index/1/index.vue': {
      routes:
        | '/install//1/'
      views:
        | never
    }
    'src/pages/install/index/2/index.vue': {
      routes:
        | '/install//2/'
      views:
        | never
    }
    'src/pages/install/index/3/index.vue': {
      routes:
        | '/install//3/'
      views:
        | never
    }
    'src/pages/install/index/4/index.vue': {
      routes:
        | '/install//4/'
      views:
        | never
    }
    'src/pages/new-install/index.vue': {
      routes:
        | '/new-install/'
      views:
        | never
    }
    'src/pages/test/index.vue': {
      routes:
        | '/test/'
      views:
        | never
    }
    'src/pages/test/page/user.vue': {
      routes:
        | '/test/page/user'
      views:
        | never
    }
    'src/pages/test/xunzhang.vue': {
      routes:
        | '/test/xunzhang'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
