// stores/main.js
import { defineStore } from 'pinia'
// import {
//   Login,
//   SetUserToken,
//   GetUserToken,
//   RemoveUserToken,
//   AutoLogin,
// } from '@/api/global.js';
export const useUserStore = defineStore('user', {
  state: () => ({
    isLogin: false,//true,//
    userToken: '',
    // user:null,
    user: {
      "user_id": 0,
      "user_group_id": 0,
      "username": "DefaultTestUser",
      "email": "00000@test.com",
      "avatar": {
        "original": "/public/static/default/user/avatars/1/original/default.png",
        "small": "/public/static/default/user/avatars/1/small/default.png",
        "middle": "/public/static/default/user/avatars/1/middle/default.png",
        "large": "/public/static/default/user/avatars/1/large/default.png"
      },
      "cover": {
        "original": "/public/static/default/user/covers/1/original/default.png",
        "small": "/public/static/default/user/covers/1/small/default.png",
        "middle": "/public/static/default/user/covers/1/middle/default.png",
        "large": "/public/static/default/user/covers/1/large/default.png"
      },
      "password": null,
      "create_ip": "127.0.0.1",
      "create_location": "create_location",
      "last_login_time": 0,
      "last_login_ip": "114.514.114.514",
      "last_login_location": "last_login_location",
      "follower_count": 0,
      "followee_count": 0,
      "following_topic_count": 0,
      "following_article_count": 0,
      "following_question_count": 0,
      "article_count": 0,
      "question_count": 0,
      "answer_count": 0,
      "comment_count": 0,
      "reply_count": 0,
      "notification_unread": 0,
      // "inbox_system": 0,
      // "inbox_user_group": 0,
      // "inbox_private_message": 0,
      "headline": "headline",
      "bio": null,
      "blog": null,
      "company": null,
      "location": "location",
      "language": "zh_CN",
      "create_time": 0,
      "update_time": 0,
      "disable_time": 0,
      "user_group": {
        "user_group_id": 0,
        "user_group_name": "Message.AdminPage.UserGroups.User",
        "user_group_description": "Message.AdminPage.UserGroups.User",
        "user_group_icon": "mdi-account",
        "user_group_icon_show": false,
        "user_group_color": "primary",
        "user_group_user_count": 0,
        "create_time": 0,
        "update_time": 0,
        "delete_time": 0,
        "is_admin": false,
        "ability_normal_login": true,
        "ability_admin_login": false,
        "ability_admin_manage_user_group": false,
        "ability_admin_manage_user": false,
        "ability_admin_manage_topic": false,
        "ability_admin_manage_question": false,
        "ability_admin_manage_article": false,
        "ability_admin_manage_comment": false,
        "ability_admin_manage_answer": false,
        "ability_admin_manage_reply": false,
        "ability_admin_manage_report": false,
        "ability_admin_manage_option": false,
        "ability_create_article": false,
        "ability_create_question": false,
        "ability_create_answer": false,
        "ability_create_comment": false,
        "ability_create_reply": false,
        "ability_create_topic": false,
        "ability_edit_own_article": false,
        "ability_edit_own_question": false,
        "ability_edit_own_answer": false,
        "ability_edit_own_comment": false,
        "ability_edit_own_reply": false,
        "ability_edit_own_topic": false,
        "ability_delete_own_article": false,
        "ability_delete_own_question": false,
        "ability_delete_own_answer": false,
        "ability_delete_own_comment": false,
        "ability_delete_own_reply": false,
        "ability_delete_own_topic": false,
        "time_before_edit_article": 0,
        "time_before_edit_question": 0,
        "time_before_edit_answer": 0,
        "time_before_edit_comment": 0,
        "time_before_edit_reply": 0,
        "time_before_edit_topic": 0,
        "time_before_delete_article": 0,
        "time_before_delete_question": 0,
        "time_before_delete_answer": 0,
        "time_before_delete_comment": 0,
        "time_before_delete_reply": 0,
        "time_before_delete_topic": 0,
        "ability_edit_article_only_no_comment": false,
        "ability_edit_question_only_no_answer": false,
        "ability_edit_answer_only_no_comment": false,
        "ability_edit_question_only_no_comment": false,
        "ability_edit_comment_only_no_reply": false,
        "ability_edit_reply_only_no_reply": false,
        "ability_edit_topic_only_no_article_or_question": false,
        "ability_delete_article_only_no_comment": false,
        "ability_delete_question_only_no_answer": false,
        "ability_delete_answer_only_no_comment": false,
        "ability_delete_question_only_no_comment": false,
        "ability_delete_comment_only_no_reply": false,
        "ability_delete_reply_only_no_reply": false,
        "ability_delete_topic_only_no_article_or_question": false,
        "ability_edit_own_info": false,
        "ability_vote": false
      }
    },
    defaultUser: {
      "user_id": 0,
      "user_group_id": 0,
      "username": "DefaultTestUser",
      "email": "00000@test.com",
      "avatar": {
        "original": "/public/static/default/user/avatars/1/original/default.png",
        "small": "/public/static/default/user/avatars/1/small/default.png",
        "middle": "/public/static/default/user/avatars/1/middle/default.png",
        "large": "/public/static/default/user/avatars/1/large/default.png"
      },
      "cover": {
        "original": "/public/static/default/user/covers/1/original/default.png",
        "small": "/public/static/default/user/covers/1/small/default.png",
        "middle": "/public/static/default/user/covers/1/middle/default.png",
        "large": "/public/static/default/user/covers/1/large/default.png"
      },
      "password": null,
      "create_ip": "127.0.0.1",
      "create_location": "create_location",
      "last_login_time": 0,
      "last_login_ip": "114.514.114.514",
      "last_login_location": "last_login_location",
      "follower_count": 0,
      "followee_count": 0,
      "following_topic_count": 0,
      "following_article_count": 0,
      "following_question_count": 0,
      "article_count": 0,
      "question_count": 0,
      "answer_count": 0,
      "comment_count": 0,
      "reply_count": 0,
      "notification_unread": 0,
      // "inbox_system": 0,
      // "inbox_user_group": 0,
      // "inbox_private_message": 0,
      "headline": "headline",
      "bio": null,
      "blog": null,
      "company": null,
      "location": "location",
      "language": "zh_CN",
      "create_time": 0,
      "update_time": 0,
      "disable_time": 0,
      "user_group": {
        "user_group_id": 0,
        "user_group_name": "Message.AdminPage.UserGroups.User",
        "user_group_description": "Message.AdminPage.UserGroups.User",
        "user_group_icon": "mdi-account",
        "user_group_icon_show": false,
        "user_group_color": "primary",
        "user_group_user_count": 0,
        "create_time": 0,
        "update_time": 0,
        "delete_time": 0,
        "is_admin": false,
        "ability_normal_login": true,
        "ability_admin_login": false,
        "ability_admin_manage_user_group": false,
        "ability_admin_manage_user": false,
        "ability_admin_manage_topic": false,
        "ability_admin_manage_question": false,
        "ability_admin_manage_article": false,
        "ability_admin_manage_comment": false,
        "ability_admin_manage_answer": false,
        "ability_admin_manage_reply": false,
        "ability_admin_manage_report": false,
        "ability_admin_manage_option": false,
        "ability_create_article": false,
        "ability_create_question": false,
        "ability_create_answer": false,
        "ability_create_comment": false,
        "ability_create_reply": false,
        "ability_create_topic": false,
        "ability_edit_own_article": false,
        "ability_edit_own_question": false,
        "ability_edit_own_answer": false,
        "ability_edit_own_comment": false,
        "ability_edit_own_reply": false,
        "ability_edit_own_topic": false,
        "ability_delete_own_article": false,
        "ability_delete_own_question": false,
        "ability_delete_own_answer": false,
        "ability_delete_own_comment": false,
        "ability_delete_own_reply": false,
        "ability_delete_own_topic": false,
        "time_before_edit_article": 0,
        "time_before_edit_question": 0,
        "time_before_edit_answer": 0,
        "time_before_edit_comment": 0,
        "time_before_edit_reply": 0,
        "time_before_edit_topic": 0,
        "time_before_delete_article": 0,
        "time_before_delete_question": 0,
        "time_before_delete_answer": 0,
        "time_before_delete_comment": 0,
        "time_before_delete_reply": 0,
        "time_before_delete_topic": 0,
        "ability_edit_article_only_no_comment": false,
        "ability_edit_question_only_no_answer": false,
        "ability_edit_answer_only_no_comment": false,
        "ability_edit_question_only_no_comment": false,
        "ability_edit_comment_only_no_reply": false,
        "ability_edit_reply_only_no_reply": false,
        "ability_edit_topic_only_no_article_or_question": false,
        "ability_delete_article_only_no_comment": false,
        "ability_delete_question_only_no_answer": false,
        "ability_delete_answer_only_no_comment": false,
        "ability_delete_question_only_no_comment": false,
        "ability_delete_comment_only_no_reply": false,
        "ability_delete_reply_only_no_reply": false,
        "ability_delete_topic_only_no_article_or_question": false,
        "ability_edit_own_info": false,
        "ability_vote": false
      }
    },
    userGroupI18NKeyValue: {
      user_group_id: "UserGroupID",
      user_group_name: "UserGroupName",
      user_group_description: "UserGroupDescription",
      user_group_icon: "UserGroupIcon",
      user_group_icon_show: "UserGroupIconShow",
      user_group_color: "UserGroupColor",
      user_group_user_count: "UserGroupUserCount",
      create_time: "CreateTime",
      update_time: "UpdateTime",
      is_admin: "IsAdmin",
      ability_normal_login: "AbilityNormalLogin",
      ability_admin_login: "AbilityAdminLogin",
      ability_admin_manage_user_group: "AbilityAdminManageUserGroup",
      ability_admin_manage_user: "AbilityAdminManageUser",
      ability_admin_manage_topic: "AbilityAdminManageTopic",
      ability_admin_manage_question: "AbilityAdminManageQuestion",
      ability_admin_manage_article: "AbilityAdminManageArticle",
      ability_admin_manage_comment: "AbilityAdminManageComment",
      ability_admin_manage_answer: "AbilityAdminManageAnswer",
      ability_admin_manage_reply: "AbilityAdminManageReply",
      ability_admin_manage_report: "AbilityAdminManageReport",
      ability_admin_manage_option: "AbilityAdminManageSetting",
      ability_create_article: "AbilityCreateArticle",
      ability_create_question: "AbilityCreateQuestion",
      ability_create_answer: "AbilityCreateAnswer",
      ability_create_comment: "AbilityCreateComment",
      ability_create_reply: "AbilityCreateReply",
      ability_create_topic: "AbilityCreateTopic",
      ability_edit_own_article: "AbilityEditOwnArticle",
      ability_edit_own_question: "AbilityEditOwnQuestion",
      ability_edit_own_answer: "AbilityEditOwnAnswer",
      ability_edit_own_comment: "AbilityEditOwnComment",
      ability_edit_own_reply: "AbilityEditOwnReply",
      ability_edit_own_topic: "AbilityEditOwnTopic",
      ability_delete_own_article: "AbilityDeleteOwnArticle",
      ability_delete_own_question: "AbilityDeleteOwnQuestion",
      ability_delete_own_answer: "AbilityDeleteOwnAnswer",
      ability_delete_own_comment: "AbilityDeleteOwnComment",
      ability_delete_own_reply: "AbilityDeleteOwnReply",
      ability_delete_own_topic: "AbilityDeleteOwnTopic",
      time_before_edit_article: "TimeBeforeEditArticle",
      time_before_edit_question: "TimeBeforeEditQuestion",
      time_before_edit_answer: "TimeBeforeEditAnswer",
      time_before_edit_comment: "TimeBeforeEditComment",
      time_before_edit_reply: "TimeBeforeEditReply",
      time_before_edit_topic: "TimeBeforeEditTopic",
      time_before_delete_article: "TimeBeforeDeleteArticle",
      time_before_delete_question: "TimeBeforeDeleteQuestion",
      time_before_delete_answer: "TimeBeforeDeleteAnswer",
      time_before_delete_comment: "TimeBeforeDeleteComment",
      time_before_delete_reply: "TimeBeforeDeleteReply",
      time_before_delete_topic: "TimeBeforeDeleteTopic",
      ability_edit_article_only_no_comment: "AbilityEditArticleOnlyNoComment",
      ability_edit_question_only_no_answer: "AbilityEditQuestionOnlyNoAnswer",
      ability_edit_answer_only_no_comment: "AbilityEditAnswerOnlyNoComment",
      ability_edit_question_only_no_comment: "AbilityEditQuestionOnlyNoComment",
      ability_edit_comment_only_no_reply: "AbilityEditCommentOnlyNoReply",
      ability_edit_reply_only_no_reply: "AbilityEditReplyOnlyNoReply",
      ability_edit_topic_only_no_article_or_question: "AbilityEditTopicOnlyNoArticleOrQuestion",
      ability_delete_article_only_no_comment: "AbilityDeleteArticleOnlyNoComment",
      ability_delete_question_only_no_answer: "AbilityDeleteQuestionOnlyNoAnswer",
      ability_delete_answer_only_no_comment: "AbilityDeleteAnswerOnlyNoComment",
      ability_delete_question_only_no_comment: "AbilityDeleteQuestionOnlyNoComment",
      ability_delete_comment_only_no_reply: "AbilityDeleteCommentOnlyNoReply",
      ability_delete_reply_only_no_reply: "AbilityDeleteReplyOnlyNoReply",
      ability_delete_topic_only_no_article_or_question: "AbilityDeleteTopicOnlyNoArticleOrQuestion",
      ability_edit_own_info: "AbilityEditOwnInfo",
      ability_vote: "AbilityVote"
    },
  }),
  getters: {
    getIsLogin: (state) => state.isLogin,
    getUserToken: (state) => state.userToken,
    getUser: (state) => state.user,
    getUserID: (state) => state.user.user_id,
    getDefaultUser: (state) => state.defaultUser,
    getUserGroupI18NKeyValue: (state) => state.user.userGroupI18NKeyValue,
  },
  actions: {
    setIsLogin(isLogin) {
      // console.log('setIsLogin',isLogin)
      this.isLogin = isLogin
      // if(isLogin==null){
      //   this.userToken = null
      //   this.user = null
      // }
    },
    setUserToken(userToken) {
      this.userToken = userToken
    },
    setUser(user) {
      this.user = user
    },
    setDefaultUser(defaultUser) {
      this.defaultUser = defaultUser
    },
    setUserGroupI18NKeyValue(userGroupI18NKeyValue) {
      this.user.userGroupI18NKeyValue = userGroupI18NKeyValue
    },
  },
})